#-------------------------------
# General Site Settings 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
title: DX area
logo: # You can add own logo. For example '/images/logo.png'.
description: Digital transformation works
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://dxarea.com/" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: David
  avatar: '/images/avatarDavid.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: DX Area
  description: Moving Forward
  image: '/images/landing.webp'


#-------------------------------
# Contact Settings
contact:
  email: dxarea@gmx.com # Add your email for contant form
  description: En DX estaremos encantados de colaborar contigo en cualquier proyecto de transformación digital. Podemos hacerlo a diversos niveles, gestión de proyectos, desarrollo, o consultorías puntuales. No dudes en ponerte en contacto con nostros y aclarar cualquier duda que puedas tener.

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown
disqus-identifier: dx-area # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed